version: '3'

networks:
  EDP:

services:
  EDPBACKcode:
    image: php:7.4-apache
    container_name: EDPCODEback
    ports:
      - 8080:80
    volumes:
      - ./EDPBACKcode:/var/www/html
    networks:
      - EDP

  EDPCODE:
    image: php:7.4-apache
    container_name: EDPcode
    ports:
      - 8081:80
    volumes:
      - ./EDPCODE:/var/www/html
    networks:
      - EDP